package rw.ac.auca.scoutpro_27202.service;

import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.List;
import com.lowagie.text.ListItem;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import rw.ac.auca.scoutpro_27202.document.ScoutingReport;
import rw.ac.auca.scoutpro_27202.domain.Assessment;
import rw.ac.auca.scoutpro_27202.domain.Athlete;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;

// Builds one downloadable PDF from an assessment and its scouting report.
// An athlete's copy contains the summary only. Staff copies include scores, strengths and weaknesses.
final class ReportPdf {

    private static final Font TITLE = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Color.BLACK);
    private static final Font HEADING = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 13, new Color(6, 78, 59));
    private static final Font BODY = FontFactory.getFont(FontFactory.HELVETICA, 11, Color.DARK_GRAY);
    private static final Font SMALL = FontFactory.getFont(FontFactory.HELVETICA, 9, Color.GRAY);

    private ReportPdf() {}

    static byte[] write(Assessment assessment, ScoutingReport report, boolean includeScores) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        Document document = new Document();
        PdfWriter.getInstance(document, out);
        document.open();

        Athlete athlete = assessment.getAthlete();
        document.add(new Paragraph("ScoutPro", SMALL));
        document.add(new Paragraph("Scouting report", TITLE));
        document.add(spacer());
        document.add(new Paragraph(athlete.getFullName(), HEADING));
        document.add(new Paragraph(
                text(athlete.getAthleteCode()) + " · " + text(athlete.getPosition())
                        + " · " + athlete.getSport().getName(),
                BODY));
        document.add(new Paragraph(
                "Assessed " + assessment.getAssessmentDate().format(DateTimeFormatter.ISO_LOCAL_DATE)
                        + " by " + assessment.getScout().getFullName()
                        + " · overall " + assessment.getOverallScore(),
                BODY));
        if (assessment.getRemarks() != null && !assessment.getRemarks().isBlank()) {
            document.add(new Paragraph("Remarks: " + assessment.getRemarks().trim(), BODY));
        }

        if (includeScores) {
            document.add(spacer());
            document.add(new Paragraph("Scores", HEADING));
            document.add(scoreTable(assessment));
        }

        document.add(spacer());
        document.add(new Paragraph("Summary", HEADING));
        document.add(new Paragraph(text(report.getSummary()), BODY));
        bullets(document, "Strengths", report.getStrengths());
        bullets(document, "Weaknesses", report.getWeaknesses());
        if (report.getTags() != null && !report.getTags().isEmpty()) {
            document.add(spacer());
            document.add(new Paragraph("Tags: " + String.join(", ", report.getTags()), BODY));
        }

        document.add(spacer());
        document.add(new Paragraph("Generated by ScoutPro. This file is a copy of the report stored for this assessment.", SMALL));
        document.close();
        return out.toByteArray();
    }

    private static PdfPTable scoreTable(Assessment assessment) {
        PdfPTable table = new PdfPTable(new float[] { 3f, 1f, 1f });
        table.setWidthPercentage(100);
        table.setSpacingBefore(6);
        header(table, "Criterion");
        header(table, "Weight");
        header(table, "Score");
        assessment.getScores().stream()
                .sorted(Comparator.comparing(score -> score.getCriterion().getName()))
                .forEach(score -> {
                    cell(table, score.getCriterion().getName());
                    cell(table, String.valueOf(score.getCriterion().getWeight()));
                    cell(table, String.valueOf(score.getScore()));
                });
        return table;
    }

    private static void bullets(Document document, String title, java.util.List<String> items) {
        if (items == null || items.isEmpty()) {
            return;
        }
        document.add(spacer());
        document.add(new Paragraph(title, HEADING));
        List list = new List(false, 14);
        for (String item : items) {
            list.add(new ListItem(item, BODY));
        }
        document.add(list);
    }

    private static void header(PdfPTable table, String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.WHITE)));
        cell.setBackgroundColor(new Color(6, 78, 59));
        cell.setPadding(6);
        table.addCell(cell);
    }

    private static void cell(PdfPTable table, String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, BODY));
        cell.setPadding(6);
        table.addCell(cell);
    }

    private static Paragraph spacer() {
        return new Paragraph(" ");
    }

    private static String text(String value) {
        return value == null || value.isBlank() ? "-" : value.trim();
    }
}
